---

- name: Gather facts
  include_tasks: facts.yml

- name: Install Python when not installed
  when: "'not found' in python_version.stdout"
  block:
    -
      name: Install Python 2
      when: ansible_bootstrap_python_version == 2
      raw: |
        if [ -x "$(command -v apt-get)" ]
        then
          apt-get update && apt-get install -y python python-apt aptitude
        elif [ -x "$(command -v yum)" ]
        then
          yum install -y python
        elif [ -x "$(command -v zypper)" ]
        then
          zypper -n --gpg-auto-import-keys refresh && zypper -n install -y python python-xml
        elif [ -x "$(command -v apk)" ]
        then
          apk update && apk add python
        elif [ -x "$(command -v pacman)" ]
        then
          pacman -Syu --noconfirm python2
        elif [ -x "$(command -v dnf)" ]
        then
          dnf --assumeyes install python python-devel python2-dnf
        elif [ -x "$(command -v emerge)" ]
        then
          emerge --ask n dev-lang/python-2
        fi
    -
      name: Install Python 3
      when: ansible_bootstrap_python_version == 3
      raw: |
        if [ -x "$(command -v apt-get)" ]
        then
          apt-get update && apt-get install -y python3 python3-apt python3-setuptools aptitude
        elif [ -x "$(command -v yum)" ]
        then
          yum install -y python3
        elif [ -x "$(command -v zypper)" ]
        then
          zypper -n --gpg-auto-import-keys refresh && zypper -n install -y python3 python3-xml
        elif [ -x "$(command -v apk)" ]
        then
          apk update && apk add python
        elif [ -x "$(command -v pacman)" ]
        then
          pacman -Syu --noconfirm python3
        elif [ -x "$(command -v dnf)" ]
        then
          dnf --assumeyes install python3 python3-devel python3-dnf
        elif [ -x "$(command -v emerge)" ]
        then
          emerge --ask n dev-lang/python-3
        fi

- name: Install some basic packages
  block:
    -
      name: Install basic packages with apt
      apt:
        name:
          - ca-certificates
          - curl
        state: present
      when: ansible_bootstrap_facts_os_name == "Ubuntu"
    -
      name: Install basic packages with yum
      yum:
        name:
          - ca-certificates
          - curl
        state: present
      when: ansible_bootstrap_facts_os_name == "CentOS"

- name: Install sudo
  when: ansible_bootstrap_with_sudo | bool
  block:
    -
      name: Install sudo with apt
      apt:
        name: sudo
        state: present
      when: ansible_bootstrap_facts_os_name == "Ubuntu"
    -
      name: Install sudo with yum
      yum:
        name: sudo
        state: present
      when: ansible_bootstrap_facts_os_name == "CentOS"
