---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ansible-bootstrap-ubuntu-18-04
    alias: ubuntu/bionic/amd64
    groups: [ "ansible-bootstrap" ]
provisioner:
  name: ansible
  playbooks:
    prepare: ../.playbooks/prepare.yml
    create: ../.playbooks/create.yml
    converge: ../.playbooks/playbook.yml
    destroy: ../.playbooks/destroy.yml
  inventory:
    links:
      group_vars: ../.inventory/group_vars/
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../.tests/
  lint:
    name: flake8
